# Site settings
title: Adrianna Frick
email: f/mvodelbp
# url: https://github.com/jeromelachaud/freelancer-theme
description: "My technical portfolio of curriculum and instructional design, web design, and writing."
keywords: "your keywords, separated by commas"
skills: "Curriculum and Instructional Designer - Web Developer - Technical Writing"
meta_author: Frick Adrianna

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 999999 #18bc9c #80B3FF
  primary-rgb: "153, 153, 153" #128,179,255"
  secondary: 395061 #234E67 #3c6780  #FD6E8A
  secondary-dark: 2C4354 #A2122F

# Footer settings
footer:
  copyright: Adrianna Frick
  social: Social Media

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/adriannafrick
  - title: linkedin
    url: https://www.linkedin.com/in/adrifrick/
  - title: github
    url: http://github.com/adriannafrick

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
